### ISSUE TITLE
Utlimaker S7

### ISSUE THREAD

**Issue by FBurkelwsd** [FBurkelwsd/Eastlake-Shop#9]
https://support.ultimaker.com/s/topic/0TO5b000000Q4uRGAS/3d-printers 

https://shop3duniverse.com/products/ultimaker-s7?msclkid=6108d08d07cf1b67cbbbb6beb3edb1f3&utm_source=bing&utm_medium=cpc&utm_campaign=Search%20-%20UltiMaker%20-%20JF&utm_term=ultimaker%20s7&utm_content=UltiMaker%20S7%3A%20Only#v45754785202496

**Comment by s-bitshaki** [comment]
Finished another bench. Printed great keep in mind this is a .4 mm nozzle so it is not ideal for smaller prints. Surprisingly it needed a whole hour ![20240502_130943.jpg](https://github.com/FBurkelwsd/Eastlake-Shop/assets/113002803/5c06c122-f04c-4689-8e7f-720e28b69b04)

**Comment by FBurkelwsd** [comment]
Moved to REdmond HS, or is waiting to move
